"""Extract Cotton UI's classes to a `@source inline(...)` file the consumer @imports,
so their own Tailwind v4 build emits the kit's utilities without scanning the
(gitignored) installed package.

    python manage.py cotton_ui_sources   # writes ./cotton-ui.sources.css
"""

from pathlib import Path

import django_cotton_ui
from django.core.management.base import BaseCommand

KIT_STATIC = Path(django_cotton_ui.__file__).parent / "static" / "django_cotton_ui"
KIT_CSS = KIT_STATIC / "cotton-ui.css"
KIT_TOKENS = KIT_STATIC / "cotton-ui.tokens.css"


def extract_candidates(css: str) -> set[str]:
    """Class candidates from compiled CSS, un-escaping Tailwind's selector escapes
    (`\\:`, `\\/`, `\\[` ...) and keeping `[...]` arbitrary values whole."""
    candidates: set[str] = set()
    boundary = set(" \n\t\r,({>+~}")
    i, n = 0, len(css)
    while i < n:
        if css[i] == "." and (i == 0 or css[i - 1] in boundary):
            j = i + 1
            buf: list[str] = []
            depth = 0  # bracket depth inside [...]
            while j < n:
                c = css[j]
                if c == "\\" and j + 1 < n:  # escaped char is literal
                    nc = css[j + 1]
                    buf.append(nc)
                    if nc == "[":
                        depth += 1
                    elif nc == "]":
                        depth -= 1
                    j += 2
                    continue
                if depth > 0:
                    if c == "]":
                        depth -= 1
                    buf.append(c)
                    j += 1
                    continue
                if c.isalnum() or c in "-_":
                    buf.append(c)
                    j += 1
                    continue
                break
            cand = "".join(buf)
            if cand and not cand[0].isdigit():
                candidates.add(cand)
            i = j
        else:
            i += 1
    return candidates


class Command(BaseCommand):
    help = "Write Cotton UI's classes to a @source inline() file for your own Tailwind build."

    def add_arguments(self, parser):
        parser.add_argument(
            "-o", "--output", default="cotton-ui.sources.css",
            help="Output file (default: ./cotton-ui.sources.css)",
        )

    def handle(self, *args, **options):
        if not KIT_CSS.exists() or not KIT_TOKENS.exists():
            self.stderr.write(self.style.ERROR(f"Kit CSS not found under {KIT_STATIC}"))
            return
        candidates = sorted(extract_candidates(KIT_CSS.read_text()))
        output = Path(options["output"])
        output.write_text(
            "/* Generated by `manage.py cotton_ui_sources`. Do not edit.\n"
            '   @import after `@import "tailwindcss"`; brand via :root / .dark after it. */\n\n'
            "@custom-variant dark (&:where(.dark, .dark *));\n\n"
            f"{KIT_TOKENS.read_text()}\n"
            f'@source inline("{" ".join(candidates)}");\n'
        )
        self.stdout.write(self.style.SUCCESS(f"Wrote tokens + {len(candidates)} classes to {output}"))
        self.stdout.write(f'Add to your Tailwind input CSS:  @import "./{output}";')
